### ISSUE TITLE
how to make a byte string object

### ISSUE THREAD

**Issue by gorazdko** [telecombretagne/YACL#5]
## Question

To my cborPair data I would like to append a byte string, e.g.

uint8_t byte_string[] = {1,2,3,4,5};

data.append("1", byte_string);

How can I do this?

By using `CBOR(const uint8_t* buffer, size_t buffer_len);` I see in cbor playground

```
A3       # map(3)
   61    # text(1)
      31 # "1"
   01    # unsigned(1)
   02    # unsigned(2)
   03    # unsigned(3)
   04    # unsigned(4)
   05    # unsigned(5)
```

What i would like to achieve is this:

```
{
  1: h'0102030405'
}
```
```
A1               # map(1)
   01            # unsigned(1)
   45            # bytes(5)
      0102030405 # "\x01\x02\x03\x04\x05"
```

**Comment by alexmrqt** [comment]
Hello,

There is no dedicated constructor for byte string (it clashes with `CBOR(const uint8_t* buffer, size_t buffer_len)` that is used for decoding).
There is also no direct possibility to append a byte string to a CBOR Pair.

What you need to do is to create a CBOR NULL, and then replace its value with `encode()`.
Then you need to append this CBOR object to your CBOR Pair.

Something along those lines should do the trick (untested):
```c++
uint8_t byte_string[] = {1,2,3,4,5};

CBOR byte_string_cbor = CBOR();
byte_string_cbor.encode(byte_string, 5);

CBORPair data = CBORPair();
data.append("1", byte_string_cbor);
```

Please let me know if that fixes your problem.

**Comment by gorazdko** [comment]
thanks, this works.
